// ─── 테마 정의 ───────────────────────────────────────────────
const THEMES = [
  {
    id: "success",
    label: "성공·기원",
    icon: "🏆",
    color: "#F59E0B",
    bg: "#FFFBEB",
    description: "합격, 취업, 창업, 승진을 축하하거나 기원할 때",
    keywords: ["합격", "취업", "창업", "승진", "성공", "기원", "응원", "졸업"],
  },
  {
    id: "love",
    label: "사랑·연애",
    icon: "💕",
    color: "#EC4899",
    bg: "#FDF2F8",
    description: "고백, 기념일, 연인에게 마음을 전하고 싶을 때",
    keywords: ["사랑", "고백", "기념일", "연인", "연애", "데이트", "프러포즈"],
  },
  {
    id: "comfort",
    label: "위로·평화",
    icon: "🕊️",
    color: "#8B5CF6",
    bg: "#F5F3FF",
    description: "힘든 일을 겪는 분께, 마음의 안정이 필요할 때",
    keywords: ["위로", "평화", "힘내", "응원", "슬픔", "상처", "치유", "안정"],
  },
  {
    id: "gratitude",
    label: "감사",
    icon: "🙏",
    color: "#10B981",
    bg: "#ECFDF5",
    description: "부모님, 선생님, 소중한 분께 감사를 전할 때",
    keywords: ["감사", "고마움", "부모님", "선생님", "스승의날", "어버이날"],
  },
  {
    id: "health",
    label: "건강·쾌유",
    icon: "💚",
    color: "#059669",
    bg: "#F0FDF4",
    description: "병문안, 쾌유를 빌 때, 건강한 앞날을 기원할 때",
    keywords: ["건강", "쾌유", "병문안", "회복", "완쾌", "입원", "수술"],
  },
  {
    id: "friendship",
    label: "우정",
    icon: "🤝",
    color: "#3B82F6",
    bg: "#EFF6FF",
    description: "친구, 동료에게 소중한 마음을 전하고 싶을 때",
    keywords: ["우정", "친구", "동료", "우리", "오랜 친구", "우의"],
  },
  {
    id: "celebration",
    label: "축하·기쁨",
    icon: "🎉",
    color: "#F97316",
    bg: "#FFF7ED",
    description: "생일, 결혼, 돌잔치 등 기쁜 순간을 함께할 때",
    keywords: ["생일", "결혼", "축하", "돌잔치", "파티", "기쁨", "행복"],
  },
  {
    id: "memorial",
    label: "추모·애도",
    icon: "🌿",
    color: "#6B7280",
    bg: "#F9FAFB",
    description: "고인을 추모하거나 위로의 마음을 전할 때",
    keywords: ["추모", "애도", "장례", "고인", "기억", "영면"],
  },
];

// ─── 꽃 데이터베이스 ───────────────────────────────────────────
// season.months: 해당 월(1~12) 배열 / [] = 연중 가능
// artificialPopularity: 조화 인기도 (1~100)
const FLOWERS = [
  // ── 장미 ──────────────────────────────
  {
    id: 1,
    name: "빨강 장미",
    englishName: "Red Rose",
    meaning: "사랑, 열정, 당신을 사랑합니다",
    themes: ["love", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["빨강"],
    emoji: "🌹",
    description: "열정과 사랑의 상징. 강렬한 빨강은 마음속 깊은 감정을 그 어떤 말보다 강하게 전달합니다.",
    tips: "프러포즈, 기념일, 발렌타인데이에 가장 클래식한 선택. 한 송이만으로도 충분한 무게감이 있습니다.",
    combinations: ["안개꽃", "리시안서스", "칼라"],
    keywords: ["사랑", "열정", "프러포즈", "고백", "발렌타인"],
    artificialPopularity: 98,
  },
  {
    id: 2,
    name: "핑크 장미",
    englishName: "Pink Rose",
    meaning: "감사, 행복한 사랑, 찬미",
    themes: ["love", "gratitude", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["핑크"],
    emoji: "🌸",
    description: "부드럽고 따뜻한 분홍빛은 감사와 애정을 동시에 담아 전달합니다. 부담 없이 마음을 전하기 좋은 꽃.",
    tips: "어버이날, 스승의날, 생일 선물로 가장 무난하고 사랑받는 선택입니다.",
    combinations: ["흰 안개꽃", "라벤더", "수국"],
    keywords: ["감사", "부모님", "선생님", "어버이날", "스승의날", "생일"],
    artificialPopularity: 95,
  },
  {
    id: 3,
    name: "흰 장미",
    englishName: "White Rose",
    meaning: "순수, 존경, 새로운 시작",
    themes: ["comfort", "gratitude", "celebration", "memorial"],
    season: { months: [], label: "연중" },
    colors: ["흰색"],
    emoji: "🤍",
    description: "순결함과 존경을 담은 흰 장미는 격식 있는 자리에 잘 어울립니다. 새로운 시작을 축하하거나 깊은 존경을 전할 때 사용됩니다.",
    tips: "결혼식, 졸업식, 추모 행사에 잘 어울립니다.",
    combinations: ["리시안서스", "칼라", "안개꽃"],
    keywords: ["순수", "존경", "결혼", "순결"],
    artificialPopularity: 88,
  },
  {
    id: 4,
    name: "노랑 장미",
    englishName: "Yellow Rose",
    meaning: "우정, 명랑함, 풍요",
    themes: ["friendship", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["노랑"],
    emoji: "💛",
    description: "밝고 경쾌한 노랑 장미는 친구에게 전하는 따뜻한 우정의 메시지입니다. 연인보다는 소중한 친구에게.",
    tips: "친구 생일, 우정 선물, 오랜 지인에게 어울립니다. 연인에게는 주의가 필요합니다.",
    combinations: ["해바라기", "노랑 거베라", "안개꽃"],
    keywords: ["우정", "친구", "명랑", "밝음", "풍요"],
    artificialPopularity: 82,
  },
  {
    id: 5,
    name: "주황 장미",
    englishName: "Orange Rose",
    meaning: "신뢰, 열정적인 사랑, 행복",
    themes: ["love", "success", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["주황"],
    emoji: "🧡",
    description: "빨강의 열정과 노랑의 밝음이 합쳐진 주황 장미는 열정적이면서도 따뜻한 감정을 전합니다.",
    tips: "연인 선물, 창업 축하 등 에너지 넘치는 자리에 잘 어울립니다.",
    combinations: ["해바라기", "거베라", "안개꽃"],
    keywords: ["열정", "신뢰", "에너지", "창업"],
    artificialPopularity: 78,
  },

  // ── 튤립 ──────────────────────────────
  {
    id: 6,
    name: "빨강 튤립",
    englishName: "Red Tulip",
    meaning: "사랑의 고백, 완벽한 사랑",
    themes: ["love"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["빨강"],
    emoji: "🌷",
    description: "장미보다 은근하게, 하지만 분명하게 사랑을 고백하는 꽃. 고백하는 설레임을 담기에 딱 좋습니다.",
    tips: "첫 고백, 봄 데이트, 화이트데이 선물로 인기 있습니다.",
    combinations: ["안개꽃", "수선화", "라넌큘러스"],
    keywords: ["고백", "첫사랑", "설레임", "봄"],
    artificialPopularity: 88,
  },
  {
    id: 7,
    name: "노랑 튤립",
    englishName: "Yellow Tulip",
    meaning: "희망, 명랑한 미소, 행복",
    themes: ["success", "celebration", "friendship"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["노랑"],
    emoji: "🌼",
    description: "봄의 설레임과 밝은 희망을 상징합니다. 새로운 시작을 응원하는 메시지를 밝고 경쾌하게 전달합니다.",
    tips: "입학, 취업, 새 출발을 앞둔 분께 봄 선물로 잘 어울립니다.",
    combinations: ["흰 튤립", "수선화", "프리지아"],
    keywords: ["희망", "새 출발", "입학", "취업", "봄"],
    artificialPopularity: 85,
  },
  {
    id: 8,
    name: "보라 튤립",
    englishName: "Purple Tulip",
    meaning: "영원한 사랑, 왕실의 품격",
    themes: ["love"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["보라"],
    emoji: "💜",
    description: "희귀하고 우아한 빛깔의 보라 튤립은 변치 않는 깊은 사랑을 의미합니다.",
    tips: "오랜 연인, 기념일, 특별한 사랑을 전할 때 선택하세요.",
    combinations: ["라벤더", "흰 리시안서스", "안개꽃"],
    keywords: ["영원", "깊은사랑", "기념일", "우아"],
    artificialPopularity: 72,
  },
  {
    id: 9,
    name: "흰 튤립",
    englishName: "White Tulip",
    meaning: "새로운 시작, 용서, 가치 있는 사람",
    themes: ["comfort", "celebration"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["흰색"],
    emoji: "🤍",
    description: "순수하고 깨끗한 마음으로 새 출발을 응원하는 꽃. 화해나 위로의 선물로도 의미가 깊습니다.",
    tips: "졸업, 입학, 화해, 위로의 선물로 적합합니다.",
    combinations: ["분홍 튤립", "수선화", "안개꽃"],
    keywords: ["새 출발", "졸업", "입학", "화해", "용서"],
    artificialPopularity: 76,
  },

  // ── 해바라기 ──────────────────────────
  {
    id: 10,
    name: "해바라기",
    englishName: "Sunflower",
    meaning: "동경, 기다림, 행복, 광명",
    themes: ["success", "celebration", "friendship"],
    season: { months: [6, 7, 8, 9], label: "여름·초가을" },
    colors: ["노랑"],
    emoji: "🌻",
    description: "태양을 닮은 밝고 강인한 해바라기. 긍정적인 에너지와 강한 의지를 상징하며, 보는 것만으로도 기분이 좋아집니다.",
    tips: "취업, 창업, 승진 기원·축하에 최고. 큰 꽃 한 송이만으로도 강한 인상을 줍니다.",
    combinations: ["노랑 장미", "안개꽃", "거베라"],
    keywords: ["취업", "창업", "승진", "합격", "응원", "밝음", "긍정"],
    artificialPopularity: 95,
  },

  // ── 국화 ──────────────────────────────
  {
    id: 11,
    name: "흰 국화",
    englishName: "White Chrysanthemum",
    meaning: "진실, 성실, 순수한 마음",
    themes: ["gratitude", "comfort", "memorial"],
    season: { months: [9, 10, 11], label: "가을" },
    colors: ["흰색"],
    emoji: "🌼",
    description: "오래도록 변하지 않는 진심과 성실함을 상징합니다. 격식 있고 진중한 마음을 전달하기에 좋습니다.",
    tips: "추모, 감사, 경의를 표하는 자리에 잘 어울립니다.",
    combinations: ["안개꽃", "흰 백합", "리시안서스"],
    keywords: ["추모", "애도", "진심", "성실", "경의"],
    artificialPopularity: 80,
  },
  {
    id: 12,
    name: "노랑 국화",
    englishName: "Yellow Chrysanthemum",
    meaning: "짝사랑, 실망한 사랑, 기다림",
    themes: ["comfort"],
    season: { months: [9, 10, 11], label: "가을" },
    colors: ["노랑"],
    emoji: "🌼",
    description: "가을의 정취와 함께 쓸쓸한 기다림의 감정을 담고 있습니다. 감성적인 위로의 선물이 될 수 있습니다.",
    tips: "위로나 감성적인 메시지를 전할 때 어울립니다.",
    combinations: ["코스모스", "억새", "핑크 국화"],
    keywords: ["가을", "위로", "기다림", "감성"],
    artificialPopularity: 65,
  },

  // ── 백합 ──────────────────────────────
  {
    id: 13,
    name: "흰 백합",
    englishName: "White Lily",
    meaning: "순수, 위엄, 청순, 변함없는 마음",
    themes: ["health", "comfort", "gratitude", "memorial"],
    season: { months: [5, 6, 7, 8], label: "늦봄·여름" },
    colors: ["흰색"],
    emoji: "🌸",
    description: "우아하고 청초한 흰 백합은 순수한 마음과 변함없는 진심을 담습니다. 향기 자체가 힐링이 되는 꽃.",
    tips: "병문안, 쾌유 기원, 추모에 많이 쓰입니다. 향기가 강하므로 밀폐 공간은 주의.",
    combinations: ["안개꽃", "흰 리시안서스", "아이리스"],
    keywords: ["병문안", "쾌유", "추모", "청순", "위엄"],
    artificialPopularity: 85,
  },
  {
    id: 14,
    name: "분홍 백합",
    englishName: "Pink Lily",
    meaning: "사랑의 기원, 부유, 화려함",
    themes: ["love", "celebration"],
    season: { months: [5, 6, 7], label: "늦봄·초여름" },
    colors: ["핑크"],
    emoji: "🌺",
    description: "화려하고 여성스러운 분홍 백합은 사랑과 번영의 기운을 전달합니다.",
    tips: "사랑을 기원하는 선물, 축하 꽃다발에 포인트로 활용하기 좋습니다.",
    combinations: ["빨강 장미", "안개꽃", "핑크 리시안서스"],
    keywords: ["사랑", "화려함", "축하"],
    artificialPopularity: 78,
  },

  // ── 수국 ──────────────────────────────
  {
    id: 15,
    name: "수국",
    englishName: "Hydrangea",
    meaning: "진심, 감사, 소녀의 꿈",
    themes: ["gratitude", "comfort", "love"],
    season: { months: [5, 6, 7, 8], label: "초여름~여름" },
    colors: ["보라", "파랑", "핑크", "흰색"],
    emoji: "💐",
    description: "풍성하게 모인 작은 꽃들이 진심을 가득 담은 것처럼 보입니다. 색에 따라 의미가 조금씩 달라져 선택의 재미가 있습니다.",
    tips: "감사 선물, 결혼식 장식, 여름 인테리어 플라워로 최고의 인기를 누립니다.",
    combinations: ["흰 장미", "라벤더", "리시안서스"],
    keywords: ["감사", "진심", "여름", "풍성함", "결혼식"],
    artificialPopularity: 92,
  },

  // ── 카네이션 ──────────────────────────
  {
    id: 16,
    name: "빨강 카네이션",
    englishName: "Red Carnation",
    meaning: "사랑, 열정, 당신을 사랑합니다",
    themes: ["love", "gratitude"],
    season: { months: [], label: "연중" },
    colors: ["빨강"],
    emoji: "🌹",
    description: "어버이날의 상징이기도 한 빨강 카네이션은 깊은 사랑과 존경을 동시에 담고 있습니다.",
    tips: "어버이날, 스승의날, 연인에게 전하는 고전적인 사랑의 표현입니다.",
    combinations: ["핑크 카네이션", "안개꽃", "리시안서스"],
    keywords: ["어버이날", "스승의날", "사랑", "존경"],
    artificialPopularity: 90,
  },
  {
    id: 17,
    name: "핑크 카네이션",
    englishName: "Pink Carnation",
    meaning: "감사, 사랑, 당신을 잊지 않겠습니다",
    themes: ["gratitude", "love", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["핑크"],
    emoji: "🌸",
    description: "사랑스럽고 따뜻한 핑크 카네이션은 감사와 애정을 함께 전하는 만능 꽃입니다.",
    tips: "어버이날, 생일, 감사 선물로 두루 활용됩니다.",
    combinations: ["빨강 카네이션", "흰 카네이션", "안개꽃"],
    keywords: ["감사", "생일", "어버이날", "사랑스러움"],
    artificialPopularity: 88,
  },
  {
    id: 18,
    name: "흰 카네이션",
    englishName: "White Carnation",
    meaning: "순수한 사랑, 존경, 순결",
    themes: ["gratitude", "memorial", "comfort"],
    season: { months: [], label: "연중" },
    colors: ["흰색"],
    emoji: "🤍",
    description: "순수하고 존경스러운 마음을 담은 흰 카네이션은 장례식과 추모 자리에서도 사용됩니다.",
    tips: "추모, 장례, 존경하는 분께 드리는 선물에 적합합니다.",
    combinations: ["흰 백합", "흰 장미", "안개꽃"],
    keywords: ["추모", "장례", "존경", "순결"],
    artificialPopularity: 75,
  },

  // ── 라벤더 ──────────────────────────
  {
    id: 19,
    name: "라벤더",
    englishName: "Lavender",
    meaning: "침묵, 우아, 신뢰, 행복한 사랑",
    themes: ["comfort", "love", "health"],
    season: { months: [5, 6, 7, 8], label: "초여름~여름" },
    colors: ["보라"],
    emoji: "💜",
    description: "향기 자체가 힐링인 라벤더는 마음의 평온을 선물합니다. 스트레스 해소와 수면에도 좋아 건강 선물로도 의미가 있습니다.",
    tips: "힘든 분께 드리는 위로 선물, 향초·입욕제와 함께 세트로 구성하면 좋습니다.",
    combinations: ["흰 장미", "수국", "에키나시아"],
    keywords: ["힐링", "위로", "평화", "수면", "향기", "스트레스"],
    artificialPopularity: 88,
  },

  // ── 안개꽃 ──────────────────────────
  {
    id: 20,
    name: "안개꽃",
    englishName: "Baby's Breath",
    meaning: "순수한 마음, 충실, 행복",
    themes: ["love", "gratitude", "friendship"],
    season: { months: [], label: "연중" },
    colors: ["흰색", "핑크"],
    emoji: "🌫️",
    description: "보조 꽃으로 자주 쓰이지만, 그 자체로 순수함과 충실한 마음을 담고 있습니다. 어떤 꽃과도 잘 어울리는 만능 파트너.",
    tips: "단독 또는 포인트 꽃과 조합해서 사용하면 풍성하고 낭만적인 꽃다발이 됩니다.",
    combinations: ["모든 꽃"],
    keywords: ["순수", "충실", "낭만", "보조꽃"],
    artificialPopularity: 90,
  },

  // ── 프리지아 ──────────────────────────
  {
    id: 21,
    name: "프리지아",
    englishName: "Freesia",
    meaning: "순결, 청순, 우정, 신뢰",
    themes: ["friendship", "health", "gratitude"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["노랑", "흰색", "보라", "핑크"],
    emoji: "🌼",
    description: "달콤하고 상큼한 향기로 봄의 시작을 알리는 프리지아. 청순하고 신뢰로운 마음을 전하기에 좋습니다.",
    tips: "친구 선물, 생일, 봄 선물로 향기와 함께 즐겁게 드리세요.",
    combinations: ["수선화", "튤립", "안개꽃"],
    keywords: ["봄", "향기", "청순", "친구", "신뢰"],
    artificialPopularity: 80,
  },

  // ── 거베라 ──────────────────────────
  {
    id: 22,
    name: "빨강 거베라",
    englishName: "Red Gerbera",
    meaning: "항상 쾌활하게, 수수한 아름다움",
    themes: ["success", "celebration", "health"],
    season: { months: [3, 4, 5, 6, 7, 8, 9], label: "봄~가을" },
    colors: ["빨강"],
    emoji: "🌺",
    description: "밝고 쾌활한 에너지를 담은 거베라는 보는 사람의 기분도 밝게 만듭니다. 긍정의 꽃.",
    tips: "병문안, 격려, 응원 선물로 기분을 밝혀주는 꽃입니다.",
    combinations: ["노랑 거베라", "해바라기", "안개꽃"],
    keywords: ["쾌활", "긍정", "병문안", "응원", "격려"],
    artificialPopularity: 85,
  },
  {
    id: 23,
    name: "노랑 거베라",
    englishName: "Yellow Gerbera",
    meaning: "모험심, 어려움을 극복, 풍요",
    themes: ["success", "friendship", "celebration"],
    season: { months: [3, 4, 5, 6, 7, 8, 9], label: "봄~가을" },
    colors: ["노랑"],
    emoji: "🌻",
    description: "밝은 노랑빛으로 도전과 극복의 의지를 표현합니다. 새로운 도전을 앞둔 사람에게 전하기 좋은 꽃.",
    tips: "창업, 새로운 시작, 도전하는 분께 응원의 의미로 전하세요.",
    combinations: ["해바라기", "주황 거베라", "안개꽃"],
    keywords: ["도전", "극복", "창업", "응원", "풍요"],
    artificialPopularity: 82,
  },

  // ── 리시안서스 ──────────────────────────
  {
    id: 24,
    name: "리시안서스",
    englishName: "Lisianthus",
    meaning: "아름다운 마음, 감수성, 우아함",
    themes: ["love", "gratitude", "celebration"],
    season: { months: [5, 6, 7, 8, 9], label: "초여름~가을" },
    colors: ["보라", "흰색", "핑크", "흰보라"],
    emoji: "🌸",
    description: "장미와 작약을 섞어놓은 듯한 우아한 자태. 화려하면서도 세련된 분위기를 자아냅니다.",
    tips: "결혼식, 고급 꽃다발, 특별한 날의 선물로 선호됩니다. 조화로 제작 시 품질이 특히 잘 재현됩니다.",
    combinations: ["장미", "안개꽃", "수국"],
    keywords: ["우아함", "결혼식", "고급", "세련"],
    artificialPopularity: 88,
  },

  // ── 알스트로메리아 ──────────────────────────
  {
    id: 25,
    name: "알스트로메리아",
    englishName: "Alstroemeria",
    meaning: "우정, 헌신, 지속되는 사랑",
    themes: ["friendship", "love", "gratitude"],
    season: { months: [], label: "연중" },
    colors: ["주황", "핑크", "노랑", "흰색"],
    emoji: "🌺",
    description: "여러 색의 줄무늬가 인상적인 알스트로메리아는 지속되는 우정과 헌신을 뜻합니다. 오래가는 꽃으로도 유명합니다.",
    tips: "오랜 친구, 진심 어린 고마움을 전할 때. 꽃이 오래가서 실용적이기도 합니다.",
    combinations: ["장미", "안개꽃", "거베라"],
    keywords: ["우정", "헌신", "오랜 친구", "실용적"],
    artificialPopularity: 75,
  },

  // ── 난초 ──────────────────────────────
  {
    id: 26,
    name: "호접란 (난초)",
    englishName: "Phalaenopsis Orchid",
    meaning: "우아함, 고상함, 당신은 아름답습니다",
    themes: ["success", "gratitude", "celebration"],
    season: { months: [], label: "연중" },
    colors: ["흰색", "보라", "핑크"],
    emoji: "🌺",
    description: "품격 있고 오래가는 호접란은 고급스러운 축하와 감사의 선물로 손꼽힙니다. 화분 형태로 오래 감상할 수 있습니다.",
    tips: "사무실 개업, 승진, 집들이, 고급 감사 선물로 최고입니다.",
    combinations: ["단독으로도 충분히 아름다운 꽃"],
    keywords: ["개업", "승진", "집들이", "고급", "화분", "품격"],
    artificialPopularity: 85,
  },

  // ── 목련 ──────────────────────────────
  {
    id: 27,
    name: "목련",
    englishName: "Magnolia",
    meaning: "숭고함, 고결함, 자연 사랑",
    themes: ["comfort", "success", "gratitude"],
    season: { months: [3, 4], label: "이른봄" },
    colors: ["흰색", "보라"],
    emoji: "🌸",
    description: "봄의 시작을 가장 먼저 알리는 목련은 고결하고 숭고한 아름다움을 담고 있습니다.",
    tips: "격식 있는 감사나 존경의 마음을 봄에 전할 때 의미 깊습니다.",
    combinations: ["수선화", "벚꽃", "흰 튤립"],
    keywords: ["고결함", "봄", "순수", "존경"],
    artificialPopularity: 70,
  },

  // ── 벚꽃 ──────────────────────────────
  {
    id: 28,
    name: "벚꽃",
    englishName: "Cherry Blossom",
    meaning: "삶의 아름다움, 정신적 사랑, 덧없음",
    themes: ["love", "comfort", "celebration"],
    season: { months: [3, 4], label: "이른봄" },
    colors: ["핑크", "흰색"],
    emoji: "🌸",
    description: "짧지만 눈부신 벚꽃처럼, 지금 이 순간의 소중함과 아름다움을 전합니다. 봄 특유의 감성적인 분위기.",
    tips: "봄 여행 기념, 봄 데이트, 감성적인 선물로 특별합니다.",
    combinations: ["안개꽃", "라넌큘러스", "핑크 튤립"],
    keywords: ["봄", "낭만", "감성", "소중함", "아름다움"],
    artificialPopularity: 82,
  },

  // ── 수선화 ──────────────────────────────
  {
    id: 29,
    name: "수선화",
    englishName: "Narcissus / Daffodil",
    meaning: "자존심, 고결함, 새로운 희망",
    themes: ["success", "comfort"],
    season: { months: [2, 3, 4], label: "이른봄" },
    colors: ["노랑", "흰색"],
    emoji: "🌼",
    description: "겨울을 이기고 가장 먼저 피어나는 수선화는 새 희망과 자존심을 상징합니다. 어려움을 이겨낸 분께 전하기 좋습니다.",
    tips: "시련을 이겨낸 분, 새 출발을 앞둔 분께 희망의 메시지로 전하세요.",
    combinations: ["히아신스", "튤립", "프리지아"],
    keywords: ["희망", "새 출발", "자존심", "봄", "극복"],
    artificialPopularity: 72,
  },

  // ── 히아신스 ──────────────────────────────
  {
    id: 30,
    name: "히아신스",
    englishName: "Hyacinth",
    meaning: "자신감, 희망, 슬픈 사랑",
    themes: ["success", "comfort"],
    season: { months: [3, 4], label: "봄" },
    colors: ["보라", "파랑", "핑크", "흰색"],
    emoji: "💜",
    description: "진한 향기와 함께 자신감과 희망을 전하는 히아신스. 보라빛은 슬픈 사랑을, 흰빛은 사랑스러움을 뜻합니다.",
    tips: "새 학기, 자신감을 북돋아 주는 선물로 특별합니다.",
    combinations: ["수선화", "튤립", "안개꽃"],
    keywords: ["자신감", "희망", "봄", "향기"],
    artificialPopularity: 68,
  },

  // ── 아이리스 ──────────────────────────────
  {
    id: 31,
    name: "아이리스 (붓꽃)",
    englishName: "Iris",
    meaning: "당신에게 전하는 메시지, 우아한 마음",
    themes: ["gratitude", "comfort"],
    season: { months: [4, 5, 6], label: "봄~초여름" },
    colors: ["보라", "파랑", "노랑", "흰색"],
    emoji: "💐",
    description: "그리스 신화 무지개의 여신 이리스에서 유래한 꽃. 전하고 싶은 마음을 우아하게 담아냅니다.",
    tips: "진심 어린 메시지와 함께 드리면 더욱 의미 있습니다.",
    combinations: ["흰 백합", "라벤더", "안개꽃"],
    keywords: ["우아함", "메시지", "감사"],
    artificialPopularity: 65,
  },

  // ── 팬지 ──────────────────────────────
  {
    id: 32,
    name: "팬지",
    englishName: "Pansy",
    meaning: "사색, 순수한 사랑, 나를 생각해줘",
    themes: ["love", "friendship"],
    season: { months: [3, 4, 5], label: "봄" },
    colors: ["보라", "노랑", "흰색", "핑크"],
    emoji: "🌸",
    description: "작고 귀여운 팬지는 '나를 생각해줘'라는 의미를 담아 소중한 사람에게 기억을 부탁하는 꽃입니다.",
    tips: "오랫동안 보지 못하는 친구, 멀리 떠나는 사람에게 전하는 선물로 의미 있습니다.",
    combinations: ["데이지", "수선화", "안개꽃"],
    keywords: ["기억", "사색", "봄", "귀여움", "친구"],
    artificialPopularity: 60,
  },

  // ── 코스모스 ──────────────────────────────
  {
    id: 33,
    name: "코스모스",
    englishName: "Cosmos",
    meaning: "소녀의 순정, 야생의 아름다움",
    themes: ["love", "comfort"],
    season: { months: [9, 10, 11], label: "가을" },
    colors: ["핑크", "흰색", "빨강"],
    emoji: "🌸",
    description: "가을 들판을 물들이는 코스모스는 순수하고 수줍은 첫사랑의 감성을 담고 있습니다.",
    tips: "가을 분위기의 낭만적인 선물, 첫사랑 감성의 데이트 선물로 어울립니다.",
    combinations: ["핑크 국화", "억새", "가을 들꽃"],
    keywords: ["가을", "낭만", "순수", "첫사랑", "감성"],
    artificialPopularity: 78,
  },

  // ── 작약 ──────────────────────────────
  {
    id: 34,
    name: "작약",
    englishName: "Peony",
    meaning: "수줍음, 행복한 결혼, 부귀영화",
    themes: ["love", "celebration"],
    season: { months: [4, 5, 6], label: "봄~초여름" },
    colors: ["핑크", "빨강", "흰색"],
    emoji: "🌸",
    description: "탐스럽고 풍성한 작약은 행복하고 풍요로운 삶을 상징합니다. 결혼식 꽃으로도 최고의 인기를 자랑합니다.",
    tips: "결혼 선물, 결혼식 장식, 봄 기념 선물로 사랑받습니다.",
    combinations: ["장미", "리시안서스", "안개꽃"],
    keywords: ["결혼", "행복", "풍요", "봄", "럭셔리"],
    artificialPopularity: 90,
  },

  // ── 데이지 ──────────────────────────────
  {
    id: 35,
    name: "데이지",
    englishName: "Daisy",
    meaning: "순수, 청결, 평화, 무한한 가능성",
    themes: ["comfort", "friendship", "health"],
    season: { months: [4, 5, 6, 7], label: "봄~여름" },
    colors: ["흰색", "핑크", "노랑"],
    emoji: "🌼",
    description: "작고 소박하지만 밝고 순수한 데이지는 꾸밈없는 진심을 전합니다. 어린 시절의 순수한 감성.",
    tips: "아이에게, 소박하지만 따뜻한 마음을 전하고 싶은 분께 선물하세요.",
    combinations: ["해바라기", "프리지아", "안개꽃"],
    keywords: ["순수", "소박함", "청결", "어린이", "평화"],
    artificialPopularity: 72,
  },

  // ── 칼라 ──────────────────────────────
  {
    id: 36,
    name: "칼라 (칼라 백합)",
    englishName: "Calla Lily",
    meaning: "화려한 아름다움, 순결, 존경",
    themes: ["success", "gratitude", "celebration", "memorial"],
    season: { months: [3, 4, 5, 6], label: "봄~초여름" },
    colors: ["흰색", "보라", "노랑", "핑크"],
    emoji: "🌸",
    description: "간결하고 우아한 선으로 세련미를 뽐내는 칼라. 모던하고 고급스러운 느낌을 원할 때 선택합니다.",
    tips: "결혼식, 졸업, 고급 선물 세트에 자주 사용됩니다.",
    combinations: ["흰 장미", "리시안서스", "안개꽃"],
    keywords: ["우아함", "결혼", "졸업", "모던", "세련"],
    artificialPopularity: 85,
  },

  // ── 라일락 ──────────────────────────────
  {
    id: 37,
    name: "라일락",
    englishName: "Lilac",
    meaning: "첫사랑의 감동, 젊음의 아름다움",
    themes: ["love", "comfort"],
    season: { months: [4, 5], label: "봄" },
    colors: ["보라", "흰색"],
    emoji: "💜",
    description: "달콤한 향기와 함께 첫사랑의 떨림과 청춘의 아름다움을 담은 라일락. 봄에만 느낄 수 있는 특별한 꽃.",
    tips: "봄 여행 기념, 첫사랑 감성의 선물, 청춘을 기억하고 싶은 분께.",
    combinations: ["흰 튤립", "수선화", "안개꽃"],
    keywords: ["첫사랑", "봄", "향기", "청춘", "낭만"],
    artificialPopularity: 75,
  },

  // ── 물망초 ──────────────────────────────
  {
    id: 38,
    name: "물망초",
    englishName: "Forget-me-not",
    meaning: "나를 잊지 마세요, 진실한 사랑",
    themes: ["love", "comfort", "friendship"],
    season: { months: [4, 5, 6], label: "봄~초여름" },
    colors: ["파랑", "핑크"],
    emoji: "💙",
    description: "작고 파란 꽃 한 송이에 '나를 기억해줘'라는 간절한 마음이 담겨 있습니다. 추억과 그리움의 꽃.",
    tips: "오래 보지 못하는 소중한 사람, 멀리 이별하는 연인에게 기억을 부탁하는 선물.",
    combinations: ["라일락", "팬지", "안개꽃"],
    keywords: ["기억", "그리움", "이별", "진심", "추억"],
    artificialPopularity: 62,
  },

  // ── 금어초 ──────────────────────────────
  {
    id: 39,
    name: "금어초",
    englishName: "Snapdragon",
    meaning: "욕망, 강한 의지, 긍정의 힘",
    themes: ["success"],
    season: { months: [4, 5, 6, 7], label: "봄~여름" },
    colors: ["빨강", "주황", "노랑", "핑크", "흰색"],
    emoji: "🌺",
    description: "용의 입처럼 생긴 독특한 모양으로 강한 의지와 욕망을 상징합니다. 강한 에너지를 전달하고 싶을 때.",
    tips: "도전과 의지를 응원하는 선물로 독특한 인상을 남길 수 있습니다.",
    combinations: ["해바라기", "거베라", "리시안서스"],
    keywords: ["강한 의지", "도전", "응원", "에너지"],
    artificialPopularity: 58,
  },

  // ── 민들레 ──────────────────────────────
  {
    id: 40,
    name: "민들레",
    englishName: "Dandelion",
    meaning: "행복, 감사하는 마음, 사랑의 신탁",
    themes: ["gratitude", "comfort", "friendship"],
    season: { months: [3, 4, 5, 6], label: "봄~초여름" },
    colors: ["노랑"],
    emoji: "🌼",
    description: "길가에 피어난 민들레처럼 소박하지만 강인한 생명력과 감사하는 마음을 담고 있습니다.",
    tips: "소박하지만 진심을 담은 선물. 어린이날, 자연을 좋아하는 분께 특별합니다.",
    combinations: ["데이지", "프리지아", "안개꽃"],
    keywords: ["소박함", "감사", "생명력", "자연"],
    artificialPopularity: 55,
  },
];

// ─── 현재 시즌 판별 ───────────────────────────────────────────
function getCurrentSeason() {
  const month = new Date().getMonth() + 1;
  if (month >= 3 && month <= 5) return "봄";
  if (month >= 6 && month <= 8) return "여름";
  if (month >= 9 && month <= 11) return "가을";
  return "겨울";
}

function getSeasonMonths(season) {
  const map = { 봄: [3,4,5], 여름: [6,7,8], 가을: [9,10,11], 겨울: [12,1,2] };
  return map[season] || [];
}

function isInSeason(flower) {
  if (!flower.season.months.length) return true; // 연중
  const month = new Date().getMonth() + 1;
  return flower.season.months.includes(month);
}

function getSeasonScore(flower) {
  if (!flower.season.months.length) return 50; // 연중
  const month = new Date().getMonth() + 1;
  if (flower.season.months.includes(month)) return 100;
  // 인접 달이면 부분 점수
  const near = flower.season.months.some(m => Math.abs(m - month) <= 1);
  return near ? 60 : 10;
}
