const THEMES = [
  {
    id: "all",
    label: "전체",
    icon: "grid_view",
    description: "모든 의도와 상황을 함께 봅니다."
  },
  {
    id: "success",
    label: "성공/응원",
    icon: "workspace_premium",
    description: "합격, 취업, 승진, 새 출발을 응원할 때",
    keywords: ["성공", "응원", "합격", "취업", "승진", "개업", "새출발", "기원"]
  },
  {
    id: "love",
    label: "사랑/연애",
    icon: "favorite",
    description: "고백, 기념일, 연인에게 마음을 전할 때",
    keywords: ["사랑", "연애", "고백", "기념일", "연인", "프로포즈"]
  },
  {
    id: "peace",
    label: "평화/위로",
    icon: "spa",
    description: "지친 마음을 달래고 조용한 위로를 전할 때",
    keywords: ["평화", "위로", "안정", "쉼", "회복", "슬픔", "응원"]
  },
  {
    id: "health",
    label: "건강/회복",
    icon: "ecg_heart",
    description: "회복, 병문안, 건강을 바라는 마음",
    keywords: ["건강", "회복", "병문안", "쾌유", "퇴원", "수술"]
  },
  {
    id: "gratitude",
    label: "감사/존경",
    icon: "volunteer_activism",
    description: "부모님, 선생님, 고마운 사람에게",
    keywords: ["감사", "존경", "고마움", "부모님", "선생님", "스승", "상사"]
  },
  {
    id: "celebration",
    label: "개업/축하",
    icon: "celebration",
    description: "개업, 집들이, 생일처럼 밝게 축하할 때",
    keywords: ["개업", "축하", "집들이", "생일", "행운", "번창"]
  },
  {
    id: "memory",
    label: "추모/기억",
    icon: "local_florist",
    description: "조용한 기억과 예의를 담아 전할 때",
    keywords: ["추모", "기억", "위로", "존경", "예의", "그리움"]
  }
];

const FILTERS = {
  sort: [
    { id: "match", label: "꽃말 적합도" },
    { id: "popular", label: "최근 인기" },
    { id: "available", label: "판매 가능" },
    { id: "season", label: "계절감" }
  ],
  colors: [
    { id: "white", label: "화이트", hex: "#f7f2e8" },
    { id: "pink", label: "핑크", hex: "#e7a7b0" },
    { id: "yellow", label: "옐로우", hex: "#e8bd4d" },
    { id: "purple", label: "퍼플", hex: "#9b89b6" },
    { id: "green", label: "그린", hex: "#8da581" },
    { id: "orange", label: "코랄", hex: "#d46f5d" }
  ],
  recipients: [
    { id: "friend", label: "친구" },
    { id: "lover", label: "연인" },
    { id: "family", label: "가족" },
    { id: "colleague", label: "동료" },
    { id: "client", label: "거래처" }
  ],
  budgets: [
    { id: "3", label: "3만원대", min: 30000, max: 49999 },
    { id: "5", label: "5만원대", min: 50000, max: 69999 },
    { id: "7", label: "7만원 이상", min: 70000, max: 200000 }
  ]
};

const QUICK_SEARCHES = [
  "합격을 앞둔 친구",
  "개업한 지인",
  "회복 중인 가족",
  "감사 인사를 전할 선생님",
  "조용한 위로가 필요한 사람"
];

const SUGGESTIONS = [
  "합격을 앞둔 친구에게 어울리는 꽃말",
  "개업 선물에 맞는 의미",
  "수술 후 회복 중인 가족에게",
  "스승의 날 감사 인사",
  "오래 만난 연인에게 부담 없는 꽃",
  "퇴사하는 동료에게 응원 메시지",
  "차분한 추모와 기억을 담은 꽃",
  "집들이 선물로 좋은 밝은 조화"
];

const FLOWERS = [
  {
    id: 1,
    name: "라넌큘러스",
    englishName: "Ranunculus",
    meaning: "매력, 성공을 향한 기대",
    situation: "합격과 새 출발을 앞둔 사람에게",
    themes: ["success", "celebration"],
    colors: ["pink", "yellow", "orange"],
    recipients: ["friend", "colleague", "family"],
    budget: "5",
    price: 56000,
    match: 96,
    popularity: 93,
    available: true,
    seasonScore: 91,
    bloom: "3-5월",
    palette: "soft-spring",
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=640&q=80",
    tags: ["합격", "응원", "봄무드"],
    reason: "화려하지만 부담스럽지 않은 겹꽃 형태가 새로운 시작을 축하하는 메시지와 잘 맞습니다.",
    combinations: ["스위트피", "화이트 장미", "유칼립투스"]
  },
  {
    id: 2,
    name: "해바라기",
    englishName: "Sunflower",
    meaning: "기다림, 밝은 성공, 긍정",
    situation: "취업, 승진, 개업처럼 에너지가 필요한 순간",
    themes: ["success", "celebration"],
    colors: ["yellow", "green"],
    recipients: ["friend", "colleague", "client"],
    budget: "5",
    price: 59000,
    match: 94,
    popularity: 97,
    available: true,
    seasonScore: 88,
    bloom: "7-9월",
    palette: "bright-yellow",
    image: "https://images.unsplash.com/photo-1470509037663-253afd7f0f51?auto=format&fit=crop&w=640&q=80",
    tags: ["성공", "개업", "긍정"],
    reason: "밝고 직관적인 인상이 강해 축하와 번창의 메시지를 빠르게 전달합니다.",
    combinations: ["솔리다고", "그린 소재", "오렌지 장미"]
  },
  {
    id: 3,
    name: "화이트 장미",
    englishName: "White Rose",
    meaning: "존경, 순수, 새로운 시작",
    situation: "감사와 예의를 차분하게 전하고 싶을 때",
    themes: ["gratitude", "memory", "peace"],
    colors: ["white", "green"],
    recipients: ["family", "colleague", "client"],
    budget: "7",
    price: 76000,
    match: 91,
    popularity: 86,
    available: true,
    seasonScore: 84,
    bloom: "연중",
    palette: "white-green",
    image: "https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=640&q=80",
    tags: ["존경", "예의", "차분함"],
    reason: "강한 감정보다 정중함과 품격이 먼저 느껴져 감사, 추모, 공식적인 선물에 안정적입니다.",
    combinations: ["리시안셔스", "스카비오사", "유칼립투스"]
  },
  {
    id: 4,
    name: "핑크 장미",
    englishName: "Pink Rose",
    meaning: "감사, 행복한 사랑, 다정함",
    situation: "부모님이나 연인에게 부드럽게 마음을 전할 때",
    themes: ["love", "gratitude", "celebration"],
    colors: ["pink", "white"],
    recipients: ["lover", "family"],
    budget: "5",
    price: 62000,
    match: 89,
    popularity: 95,
    available: true,
    seasonScore: 86,
    bloom: "연중",
    palette: "rose-blush",
    image: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?auto=format&fit=crop&w=640&q=80",
    tags: ["감사", "연인", "부모님"],
    reason: "사랑의 의미가 있지만 붉은 장미보다 온도가 낮아 감사와 다정함을 함께 표현하기 좋습니다.",
    combinations: ["안개꽃", "피치 카네이션", "라그라스"]
  },
  {
    id: 5,
    name: "카네이션",
    englishName: "Carnation",
    meaning: "존경, 감사, 변치 않는 사랑",
    situation: "부모님, 선생님, 오래 도와준 사람에게",
    themes: ["gratitude", "health"],
    colors: ["pink", "white", "orange"],
    recipients: ["family", "colleague"],
    budget: "3",
    price: 39000,
    match: 95,
    popularity: 88,
    available: true,
    seasonScore: 82,
    bloom: "4-6월",
    palette: "warm-pink",
    image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=640&q=80",
    tags: ["감사", "존경", "가족"],
    reason: "감사의 상징성이 뚜렷해서 메시지 오해가 적고, 조화 상품으로도 가장 안정적인 선택입니다.",
    combinations: ["핑크 장미", "화이트 소재", "그린 소재"]
  },
  {
    id: 6,
    name: "라벤더",
    englishName: "Lavender",
    meaning: "평온, 치유, 기다림",
    situation: "지친 사람에게 조용한 안정감을 주고 싶을 때",
    themes: ["peace", "health"],
    colors: ["purple", "green"],
    recipients: ["friend", "family", "lover"],
    budget: "3",
    price: 34000,
    match: 93,
    popularity: 84,
    available: true,
    seasonScore: 90,
    bloom: "6-8월",
    palette: "lavender-mist",
    image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=640&q=80",
    tags: ["위로", "회복", "평온"],
    reason: "향을 떠올리게 하는 색감과 의미가 마음을 가라앉히는 선물에 잘 맞습니다.",
    combinations: ["화이트 데이지", "유칼립투스", "스태티스"]
  },
  {
    id: 7,
    name: "데이지",
    englishName: "Daisy",
    meaning: "희망, 순수, 평화",
    situation: "가벼운 위로나 친구에게 건네는 응원",
    themes: ["peace", "success", "gratitude"],
    colors: ["white", "yellow", "green"],
    recipients: ["friend", "family"],
    budget: "3",
    price: 32000,
    match: 86,
    popularity: 81,
    available: true,
    seasonScore: 87,
    bloom: "3-6월",
    palette: "white-yellow",
    image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=640&q=80",
    tags: ["희망", "친구", "가벼운선물"],
    reason: "밝지만 과하지 않아 부담 없는 응원, 안부 선물에 적합합니다.",
    combinations: ["라벤더", "미니 장미", "그린 소재"]
  },
  {
    id: 8,
    name: "튤립",
    englishName: "Tulip",
    meaning: "고백, 배려, 새로운 시작",
    situation: "봄의 시작처럼 산뜻한 마음을 전하고 싶을 때",
    themes: ["love", "success", "celebration"],
    colors: ["pink", "yellow", "white", "purple"],
    recipients: ["lover", "friend", "colleague"],
    budget: "5",
    price: 54000,
    match: 88,
    popularity: 92,
    available: true,
    seasonScore: 96,
    bloom: "3-5월",
    palette: "spring-mix",
    image: "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=640&q=80",
    tags: ["새출발", "고백", "봄"],
    reason: "의미가 넓고 색상 선택지가 많아 연애, 응원, 축하 사이에서 조절하기 쉽습니다.",
    combinations: ["라넌큘러스", "스위트피", "안개꽃"]
  },
  {
    id: 9,
    name: "스위트피",
    englishName: "Sweet Pea",
    meaning: "출발, 감사한 작별, 즐거운 추억",
    situation: "졸업, 이직, 새로운 도전을 앞둔 사람에게",
    themes: ["success", "gratitude", "peace"],
    colors: ["pink", "purple", "white"],
    recipients: ["friend", "colleague"],
    budget: "5",
    price: 51000,
    match: 90,
    popularity: 79,
    available: false,
    seasonScore: 89,
    bloom: "4-6월",
    palette: "pastel-mix",
    image: "https://images.unsplash.com/photo-1496857239036-1fb137683000?auto=format&fit=crop&w=640&q=80",
    tags: ["졸업", "이직", "작별"],
    reason: "헤어짐의 아쉬움보다 다음 단계를 응원하는 뉘앙스가 강해 전환기의 선물에 좋습니다.",
    combinations: ["튤립", "화이트 장미", "라그라스"]
  },
  {
    id: 10,
    name: "리시안셔스",
    englishName: "Lisianthus",
    meaning: "변치 않는 사랑, 감사",
    situation: "오래 곁에 있어준 사람에게 정중하게",
    themes: ["gratitude", "love", "memory"],
    colors: ["white", "purple", "pink"],
    recipients: ["family", "lover", "client"],
    budget: "7",
    price: 72000,
    match: 92,
    popularity: 87,
    available: true,
    seasonScore: 78,
    bloom: "6-9월",
    palette: "elegant-white",
    image: "https://images.unsplash.com/photo-1522748906645-95d8adfd52c7?auto=format&fit=crop&w=640&q=80",
    tags: ["감사", "품격", "오래된마음"],
    reason: "장미보다 덜 직접적이면서도 고급스러운 인상이 있어 정중한 감사 선물에 어울립니다.",
    combinations: ["화이트 장미", "스카비오사", "그린 소재"]
  },
  {
    id: 11,
    name: "아이리스",
    englishName: "Iris",
    meaning: "좋은 소식, 지혜, 믿음",
    situation: "중요한 발표나 결과를 기다리는 사람에게",
    themes: ["success", "gratitude"],
    colors: ["purple", "white"],
    recipients: ["friend", "colleague", "client"],
    budget: "7",
    price: 74000,
    match: 87,
    popularity: 74,
    available: true,
    seasonScore: 85,
    bloom: "5-6월",
    palette: "deep-purple",
    image: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=640&q=80",
    tags: ["좋은소식", "믿음", "성과"],
    reason: "성공을 직접적으로 외치기보다 신뢰와 품격을 담아 전하고 싶을 때 좋습니다.",
    combinations: ["화이트 장미", "라벤더", "유칼립투스"]
  },
  {
    id: 12,
    name: "스태티스",
    englishName: "Statice",
    meaning: "변치 않는 기억, 영원함",
    situation: "추모, 기억, 오래 남기고 싶은 마음",
    themes: ["memory", "peace", "gratitude"],
    colors: ["purple", "white", "yellow"],
    recipients: ["family", "colleague"],
    budget: "3",
    price: 36000,
    match: 91,
    popularity: 76,
    available: true,
    seasonScore: 80,
    bloom: "5-9월",
    palette: "soft-memory",
    image: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=640&q=80",
    tags: ["추모", "기억", "영원함"],
    reason: "드라이 플라워와 조화 모두에서 오래 남는 이미지가 강해 기억의 의미를 안정적으로 전달합니다.",
    combinations: ["화이트 장미", "라벤더", "리시안셔스"]
  }
];
